apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-catalog
  labels:
    app: mysql-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-catalog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-catalog
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-cat-service
spec:
  type: ClusterIP
  selector:
    app: mysql-catalog
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/catalogo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-out-service
spec:
  type: NodePort
  selector:
    app: mysql-catalog
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30101


